services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./MenuTrix-back-end/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  api:
    container_name: api
    build: ./MenuTrix-back-end
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file:
      - ./MenuTrix-back-end/.env

  spa:
    container_name: react
    build: ./MenuTrix-front-end
    volumes:
      - react-volume:/var/www/html

  nginx:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 8080:80
      - 80:80
      - 443:443
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - db
      - api
      - spa

volumes:
  postgres-volume:
  react-volume:
