services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./MenuTrix-back-end/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  api:
    container_name: node_app
    build: ./MenuTrix-back-end
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - ./MenuTrix-back-end/.env

  spa:
    container_name: react
    build: ./MenuTrix-front-end
    volumes:
      - react-volume:/var/www/html

  openssl:
    build: ./openssl
    volumes:
      - ssl-certs:/certs

  nginx:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 8080:80
      - 443:443
    volumes:
      - react-volume:/var/www/html
      - ssl-certs:/certs
    depends_on:
      - db
      - api
      - spa
      - openssl

volumes:
  postgres-volume:
  react-volume:
  ssl-certs:
