services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./MenuTrix-back-end/.env.test
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  api:
    container_name: api
    build: ./MenuTrix-back-end
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file:
      - ./MenuTrix-back-end/.env.test

volumes:
  postgres-volume:
