on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_PORT: ${{secrets.PORT}}
          envkey_POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DATABASE: ${{secrets.POSTGRES_DATABASE}}
          envkey_POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
          envkey_POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          envkey_JWT_SECRET: ${{secrets.JWT_SECRET}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          directory: MenuTrix-back-end
          file_name: .env
          fail_on_empty: true
      - name: Create front-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_VITE_APP_API_BASE_URL: ${{secrets.VITE_APP_API_BASE_URL}}
          directory: MenuTrix-front-end
          file_name: .env
          fail_on_empty: true
      - name: Run docker compose down -v
        run: docker compose down
      - name: Delete react docker volume
        run: if docker volume ls --quiet --filter name=menutrix_fullstack_react-volume | grep -q .; then docker volume rm menutrix_fullstack_react-volume; fi
      - name: Run docker compose up
        run: docker compose up --build -d
