name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest #github nos fornecerá a máquina.
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USERNAME: 'postgres'
          envkey_POSTGRES_PASSWORD: 'postgres'
          envkey_PORT: 4000
          envkey_JWT_SECRET: 'top_secret'
          envkey_POSTGRES_HOST: 'postgres'
          envkey_POSTGRES_PORT: '5432'
          envkey_POSTGRES_DB: 'menu_trix'
          envkey_DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/menu_trix?schema=public'
          directory: MenuTrix-back-end
          file_name: .env.test
          fail_on_empty: true
      - name: Run tests
        run: docker compose -f docker-compose-tests.yml run api npm run test
